<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181031202517 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009156, 'Apocalypse', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/f/e0/526166076a1d0', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009165, 'Avengers', 'Earth''s Mightiest Heroes joined forces to take on threats that were too big for any one hero to tackle. With a roster that has included Captain America, Iron Man, Ant-Man, Hulk, Thor, Wasp and dozens more over the years, the Avengers have come to be regarded as Earth''s No. 1 team.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/20/5102c774ebae7', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009175, 'Beast', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/2/80/511a79a0451a3', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009211, 'Bucky', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/d/03/4dc8478464008', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009215, 'Luke Cage', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/a0/5112d8b6e596c', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009220, 'Captain America', 'Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America''s one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009223, 'Captain Britain', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/50/4dbf0e5d57226', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009228, 'Sharon Carter', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/d0/4ce59f2323b88', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009281, 'Doctor Doom', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/3/60/53176bb096d17', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009282, 'Doctor Strange', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/f0/5261a85a501fe', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009294, 'Exiles', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/f/c0/4ce59fbab92f5', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009312, 'Galactus', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/03/528d31a791308', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009338, 'Hawkeye', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/e/90/50fecaf4f101b', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009351, 'Hulk', 'Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009367, 'Iron Fist (Danny Rand)', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/3/f0/52616788ebc63', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009368, 'Iron Man', 'Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009378, 'Jessica Jones', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009384, 'Kang', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/4/30/52695ed19538d', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009406, 'Lockjaw', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/20/4c003d64a5a99', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009412, 'Madame Hydra', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/c/20/4d5c39a54b1dd', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009438, 'Medusa', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/c/30/537bb549bebd0', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009452, 'Moon Knight', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/3/30/52028af90e516', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009466, 'Namor', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/e/90/50febf4ae101d', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009524, 'Quicksilver', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/f0/53176ffc42f58', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009547, 'Natasha Romanoff', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009608, 'Spider-Woman (Jessica Drew)', 'When young Jessica Drew suffered uranium poisoning in 1931, her father was forced to inject her with his untested spider serum and seal her in a genetic accelerator.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/b/50/5265479097743', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009610, 'Spider-Man', 'Bitten by a radioactive spider, high school student Peter Parker gained the speed, strength and powers of a spider. Adopting the name Spider-Man, Peter hoped to start a career using his new abilities. Taught that with great power comes great responsibility, Spidey has vowed to use his powers to help people.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/3/50/526548a343e4b', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009629, 'Storm', 'Ororo Monroe is the descendant of an ancient line of African priestesses, all of whom have white hair, blue eyes, and the potential to wield magic.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/40/526963dad214d', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009652, 'Thanos', 'The Mad Titan Thanos, a melancholy, brooding individual, consumed with the concept of death, sought out personal power and increased strength, endowing himself with cybernetic implants until he became more powerful than any of his brethren.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/40/5274137e3e2cd', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009662, 'Thing', 'The radiation that mutated Reed Richards, Sue Storm and Johnny Storm into superhuman beings had also mutated Ben Grimm, transforming him into a grotesque, rock-hided strongman dubbed the Thing.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/00/527bb4d36b5c2', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009664, 'Thor', 'As the Norse God of thunder and lightning, Thor wields one of the greatest weapons ever made, the enchanted hammer Mjolnir. While others have described Thor as an over-muscled, oafish imbecile, he''s quite smart and compassionate.  He''s self-assured, and he would never, ever stop fighting for a worthwhile cause.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/d/d0/5269657a74350', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009683, 'Uatu The Watcher', 'Uatu grew so fond of the lifeforms he observed that he occasionally violated his vow of non-interference when Earth''s existence was threatened.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/03/5274135912e8d', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009685, 'Ultron', 'Arguably the greatest and certainly the most horrific creation of scientific genius Dr. Henry Pym, Ultron is a criminally insane rogue sentient robot dedicated to conquest and the extermination of humanity.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/3/70/5261a838e93c0', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009697, 'Vision', 'The metal monstrosity called Ultron created the synthetic humanoid known as the Vision from the remains of the original android Human Torch of the 1940s to serve as a vehicle of vengeance against the Avengers.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/d0/5111527040594', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009707, 'Wasp', 'When Janet Van Dyne\'s father died, she convinced her father''s associate Hank Pym to give her a supply of \"Pym particles\"; Pym also subjected her to a procedure which granted her the ability to, upon shrinking, grow wings and fire blasts of energy, which she called her \"wasp''s stings . \"', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/9/c0/5390dfd5ef165', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009718, 'Wolverine', 'Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he''s a premiere member of both the X-Men and the Avengers.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009719, 'Wonder Man', 'Simon Williams agreed to undergo an experiment to give him superhuman powers, and Baron Zemo gave him the costumed guise of Wonder Man, warning Simon that he would die without further treatments from Zemo in order to ensure his loyalty, but Simon betrayed Zemo to the Avengers and ultimately joined their ranks.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/40/4ce5a205a2322', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009726, 'X-Men', 'Feared and hated by humans because they''re different, the X-Men are heroic mutants, individuals born with special powers who''ve sworn to use their gifts to protect mutants as well as humans.', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/8/03/510c08f345938', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1009733, 'Charles Xavier', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010326, 'Steve Rogers', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010338, 'Captain Marvel (Carol Danvers)', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/6/80/5269608c1be7a', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010352, 'Madame Masque', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/00/4ce5a251c1100', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010726, 'M.O.D.O.K.', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/0/03/526034ba37851', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010758, 'Illuminati', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/70/526033bb40a5e', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010801, 'Ant-Man (Scott Lang)', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/e/20/52696868356a0', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1010926, 'Giant-Man (Ultimate)', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/d0/4c00343fc70c8', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1011072, 'Edwin Jarvis', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/40/4c0030e231f6b', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1011116, 'Killraven', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1011244, 'Mr. Negative', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/8/70/4c002efc322e3', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1011323, 'Sentinels', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/4/50/4ce5a66693659', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1011335, 'Maria Hill', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/a/00/535ff3f5397cb', 'jpg')");
        $this->addSql("INSERT INTO characters (id, name, description, liked, thumbnail_path, thumbnail_extension) VALUES (1011360, 'Red Hulk', '', 0, 'http://i.annihil.us/u/prod/marvel/i/mg/5/90/5102cb7fc1262', 'jpg')");
    }
    
    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('TRUNCATE TABLE characters');
    }
        
}