#!/bin/bash
set -e

# Make sure the database is available
until php bin/console doctrine:query:sql -q "Select true"; do
  echo "MySQL is unavailable - sleeping 1 second"
  sleep 1
done
echo "MySQL is up - starting web frontend"

#Execute migrations
php bin/console doctrine:migrations:migrate --no-interaction

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"